version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    volumes:
      - 
    networks:
      - 
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      #- '$GITLAB_HOME/logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    #environment:
    #  GITLAB_OMNIBUS_CONFIG: |
    #    external_url 'http://gitlab.example.com:8929'
    #    gitlab_rails['gitlab_shell_ssh_port'] = 2224
    env_file:
      - ./settings.env.default

volumes:
  gitlab_config:
  gitlab_data:
